server:
  port: 8080
spring:
  application:
    name: smart-parking
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/parking?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

alipay:
  appId: 2021000122620832
  appPrivateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDVYaxD3y2y0lkoeAi9uRLLSziJD1NoCH+++Q5GzoskONITWXGSbyHCefXNiinTpoe2idwuF8xSuOqnDw7bnuHl+mt+v//yqDoK+Q0vvicMAcSOaNo2777tl2m+TWDkeMfujkKflPHnLgnM0BMOBRGG8TGrWxakQ0aIC0QvaRSS0rhBdKRVgaIeJi/jA7K6/wfsvarGHrFYXqJACf8g4i+guRFhziCev8FWmnmoxHW/DSnLA43IWj2GKOPSAQ4GKP8UjkbRTa/xcyy5cVXcPVguMHu9dbH5kRYWy35h6hjKCl9ILI/PKJCmGv2BZDZbbNe4yB2sueULAOFz0+YU8nwfAgMBAAECggEAAysBELzmg8olsrkdgBuYUNZcD4TfuyKtKtutv5VfcXk6fTkNu5vUx3tiD9wmRNMrHqWrVC/cQ7olGbfag543Ql/WarpVBXhD7FfIP1Y2ZDI+hdK+sqQalJJz6nRhpOK6LSuFh7MBaGpBkP3h2opuuS8pip6+lk+9Y1WvfHi16nwZeXWysUGrZ8/PCPvz5ER+urlqa7IAbhKbNVDVHk6jbXvRvpJk62cUozc3FuPkgbreiZDKlkCfI71YG9HrIrsllaMerqIWOZB46dvzW0smPRTw6e5cmcMzgYUFLrVBLxkVkjI8B3wTAYJliQokApaWzVvyHV/rZzwZBZ7gDqY3yQKBgQDsUnUB+k7RWeTPtjrIEIin60/lyPwIwnkkmimkEoTCcd+A7h9lUDzw0YBh88qtUhO6JLJJrYXzzCnt++mvqbCPwOkyUhZr2nrwfoyvF1GEc9roulZqaEh5GM9Y25lW4Y9qpzcVPn5eob27SJvsJ1rfn35K3wVjGFDbJQ1yvY5UQwKBgQDnJjR6YF2G+I6BYWinQNslAzt6gFAkfORdToPkXAtoaj8P9E3Hudt4TVzXOAGSU1q21h2oVfkE9h6SmlwM5CheSCVkBO7zJUHHUyJsjx1p5jmvuWFxGvBnIRo4A3AYYGKS8YUS+eEOFNV8QMLAaIiGtvQwpbRNjLwPU80c58NI9QKBgAcJ7bJBYleZ9da59sY+t9NIjvipI9ie8jzE2rioVIv2GFIexZCe8zG5C7nfKQpAh5Xjweuv322DhzwvZKZ2x2uAs3FsQH614zOGkWolp6fqS3rjEe/Za08wDfz3jXmo/jyO/nUDh4AKETyizQIbqfk/JuPUALUS5FWipOPmAXdBAoGAPiq+TnOAc/6BhTaHiQQebFP0OTwtUcLtQFMPkelXgBujHk1cZe0Mo8xavd9oPMyCR05K561HrhfrnQ4615S9bq4EsGPLSEWq7UrkpUHQbVzoAuTe2iaepX33qTzzdvrlSBQA8FuYNctQp3xbZJg4r9Kg1jyaw4ioQ48MSUvj78kCgYBKLH2xhTP6SmxYOOni5WucXWa+GJ9D/dPGpixrqaOUiUCrr9wVAI8fvQRbLKQmC4dbpW2yJ9N8csZhGae+P+ZQeqQOIvXAwkD7o1ekHyTAsZ64nPXycq7QSbHe7IVNFyP5p4ddcf2GBE0TyWBAYPyO+qJ65vq2eVKZRrD6UyJqrw==
  alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiyQg042DEmOxlfnxyYlsEIfcQTv8KFuBaXvs7o6tJGv6GDpQXr+g/MtNfgef15b/m5Li1SorRRtmioijNQ/T7v3nXIMae2pAp6eVjVI4hScyKoXHPwgcFPHvpo+pJ+98tdh9SqiMpm4UVLE6CzNVTByVwbfonARDOkPjtQG45UomPTEnaiDf8S0lVSCVyCUJssur1j6dYPQFDjquaGX862q3EiYXUUQvm9nURoVl99DuWfNueO/yCtyLUZyYJ25IGB7nf5iXbbxHqptMnBX1jgL92Yyad/mDuYhBrx0Gb9GN+Xx/XzVzDkJ1NJjIFsXnG1diwUu6jJCBSqQFzTiMEQIDAQAB
  notifyUrl:   http://dcr7cd.natappfree.cc/order/notify


